on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Building
env:
    GO111MODULE: on

permissions:
    contents: read

jobs:
    build:
        name: "${{ matrix.platform }} - ${{ matrix.go-version }}"
        permissions:
            actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
            contents: read  # for actions/checkout to fetch code
        strategy:
            matrix:
                go-version: [1.19.x, 1.20.x]
                platform: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Cancel previous workflow
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go-version }}
            - uses: actions/checkout@v3

            - name: Build
              run: go build ./...
